print(f"{' ' * 7}A")
print(f"{' ' * 6}B B")
print(f"{' ' * 5}C{' ' * 3}C")
print(f"{' ' * 4}D{' ' * 5}D")
print(f"{' ' * 3}E{' ' * 7}E")
print(f"{' ' * 4}D{' ' * 5}D")
print(f"{' ' * 5}C{' ' * 3}C")
print(f"{' ' * 6}B B")
print(f"{' ' * 7}A")